// The order of this array is the canonical catalogue order used everywhere:
// the navbar dropdown, the home category grid and the "Category" sort on
// /products all follow it, so products never appear scattered.
export const categories = [
  { id: 'drinks-and-juices', title: 'Drinks and Juices', slug: 'drinks-and-juices', accent: '#D97706', description: 'Refreshing juices and drinks' },
  { id: 'dry-fruits-bulk', title: 'Dry Fruits in Bulk', slug: 'dry-fruits-bulk', accent: '#8B5A2B', description: 'Premium dry fruits supplied loose in bulk' },
  { id: 'dry-fruits-packing', title: 'Dry Fruits in Packing', slug: 'dry-fruits-packing', accent: '#A56B32', description: 'Retail-packed premium dry fruits' },
  { id: 'spices', title: 'Spices', slug: 'spices', accent: '#B91C1C', description: 'Aromatic spices and blends' },
  { id: 'edible-gums-and-resins', title: 'Natural Gums and Seeds', slug: 'edible-gums-and-resins', accent: '#B98A3C', description: 'Natural gums, resins and seeds' },
  { id: 'fried-onion', title: 'Fried Onion', slug: 'fried-onion', accent: '#C7842B', description: 'Crisp golden fried onion flakes, drained to a low oil content. Ready to use in biryani, salads, soups and garnishing.' },
  { id: 'vermicellis', title: 'Vermicelli', slug: 'vermicellis', accent: '#C7A24A', description: 'Quality vermicelli products' },
  { id: 'sweets-and-confectionery', title: 'Sweets and Confectionery', slug: 'sweets-and-confectionery', accent: '#D4568B', description: 'Traditional sweets and confectionery' },
  { id: 'exclusive-products-saag-halwa', title: 'Exclusive Products Saag', slug: 'exclusive-products-saag-halwa', accent: '#6B3F1D', description: 'Authentic ready-to-serve Punjabi saag' },
  { id: 'desi-ghee', title: 'Desi Ghee', slug: 'desi-ghee', accent: '#C79A24', description: 'Pure clarified butter (desi ghee)' },
  { id: 'pickle-achar', title: 'Achar', slug: 'pickle-achar', accent: '#7F1D1D', description: 'Traditional pickles and achar' },
  { id: 'salts', title: 'Salt', slug: 'salts', accent: '#E8A0A0', description: 'Himalayan pink salt, rock salt and fine salts' },
  { id: 'honey', title: 'Honey', slug: 'honey', accent: '#F5C518', description: 'Natural honey products' },
  { id: 'sauces', title: 'Sauces', slug: 'sauces', accent: '#D97706', description: 'Sauces and condiments' },
  { id: 'arqiyaat', title: 'Arqiyaat', slug: 'arqiyaat', accent: '#4A8B1F', description: 'Traditional arqiyaat range' },
  { id: 'tea', title: 'Tea', slug: 'tea', accent: '#31572C', description: 'Everyday and premium tea' },
  { id: 'snacks', title: 'Snacks', slug: 'snacks', accent: '#D97706', description: 'Tasty snacks and nimko' },
  { id: 'utensils-kitchenware', title: 'Kitchen & Utensils', slug: 'utensils-kitchenware', accent: '#1F2937', description: 'Kitchenware and utensils' },
  { id: 'miscellanous', title: 'Miscellaneous', slug: 'miscellanous', accent: '#2D5016', description: 'Miscellaneous food items' },
]

export const products = [
  {
    id: 'golden-raisin',
    title: 'Golden Raisin',
    slug: 'golden-raisin',
    category: 'dry-fruits-packing',
    image: '/products/dry-fruits-packing/golden-raisin.webp',
    description: 'Plump golden raisins with a soft texture and clean, natural sweetness. Widely used in bakery, confectionery, rice dishes and everyday snacking. Available in 200 g and 400 g retail packs — custom packing also made to order.',
    weight: '200 g & 400 g',
    featured: false,
  },
  {
    id: 'dry-plum',
    title: 'Dry Plum (Aloo Bukhara)',
    slug: 'dry-plum',
    category: 'dry-fruits-packing',
    image: '/products/dry-fruits-packing/dry-plum.webp',
    description: 'Tangy sun-dried plums (aloo bukhara) with a firm bite and bright, sharp flavour. A traditional favourite for chutneys, curries, compotes and direct snacking. Available in 200 g and 400 g retail packs — custom packing also made to order.',
    weight: '200 g & 400 g',
    featured: false,
  },
  {
    id: 'dry-munaka',
    title: 'Dry Munaka',
    slug: 'dry-munaka',
    category: 'dry-fruits-packing',
    image: '/products/dry-fruits-packing/dry-munaka.webp',
    description: 'Premium dried munaka — large, seeded raisins prized for their rich sweetness and soft texture. Traditionally used in desserts, tonics and festive preparations. Available in 200 g and 400 g retail packs — custom packing also made to order.',
    weight: '200 g & 400 g',
    featured: true,
  },
  {
    id: 'black-raisin',
    title: 'Black Raisin',
    slug: 'black-raisin',
    category: 'dry-fruits-packing',
    image: '/products/dry-fruits-packing/black-raisin.webp',
    description: 'Naturally dried black raisins, soft-textured with a deep, mellow sweetness. Cleaned and graded for bakery, confectionery and retail packing. Available in 200 g and 400 g retail packs — custom packing also made to order.',
    weight: '200 g & 400 g',
    featured: true,
  },
  {
    id: 'dry-fig-200g',
    title: 'Dry Fig (Anjeer)',
    slug: 'dry-fig-200g',
    category: 'dry-fruits-packing',
    image: '/products/dry-fruits-packing/dry-fig-200g.webp',
    description: 'Whole dried figs (anjeer), sun-cured to keep their natural sugars and chewy texture. A high-fibre snack that also works well in baking and dessert making. Available in 200 g and 400 g retail packs — custom packing also made to order.',
    weight: '200 g & 400 g',
    featured: false,
  },
  {
    id: 'black-seeds-kalonji',
    title: 'Black Seeds (Kalonji)',
    slug: 'black-seeds-kalonji',
    category: 'spices',
    image: '/products/spices/black-seeds-kalonji.webp',
    description: 'Premium nigella seeds (kalonji), cleaned and sorted for uniform quality. A staple aromatic for breads, pickles and spice blends across South Asia and the Middle East.',
    weight: '14oz',
    featured: true,
  },
  {
    id: 'cinnamon-flat-sticks',
    title: 'Cinnamon Flat Sticks',
    slug: 'cinnamon-flat-sticks',
    category: 'spices',
    image: '/products/spices/cinnamon-flat-sticks.webp',
    description: 'Aromatic flat cinnamon quills with a warm, woody sweetness. Ideal for slow-cooked curries, pilaf and spiced teas.',
    weight: '7oz',
    featured: true,
  },
  {
    id: 'cinnamon-round-sticks',
    title: 'Cinnamon Round Sticks',
    slug: 'cinnamon-round-sticks',
    category: 'spices',
    image: '/products/spices/cinnamon-round-sticks.webp',
    description: 'Tightly rolled round cinnamon quills with a strong, sweet aroma. Well suited to desserts, mulled drinks and premium spice retail.',
    weight: '7oz',
    featured: false,
  },
  {
    id: 'cumin-seeds-jar',
    title: 'Cumin Seeds (Jar)',
    slug: 'cumin-seeds-jar',
    category: 'spices',
    image: '/products/spices/cumin-seeds-jar.webp',
    description: 'Whole cumin seeds with a warm, earthy aroma, packed in a sealed jar for shelf presentation. An everyday essential across South Asian and Middle Eastern kitchens.',
    weight: '14oz',
    featured: true,
  },
  {
    id: 'cumin-seeds-pouch',
    title: 'Cumin Seeds (Pouch)',
    slug: 'cumin-seeds-pouch',
    category: 'spices',
    image: '/products/spices/cumin-seeds-pouch.webp',
    description: 'Whole cumin seeds in a resealable stand-up pouch — an economical format for food service and high-turnover retail.',
    weight: '14oz',
    featured: false,
  },
  {
    id: 'fennel-seeds',
    title: 'Fennel Seeds (Saunf)',
    slug: 'fennel-seeds',
    category: 'spices',
    image: '/products/spices/fennel-seeds.webp',
    description: 'Sweet, aromatic fennel seeds (saunf), cleaned and graded. Used in cooking, spice blends and as a traditional after-meal mouth freshener.',
    weight: '14oz',
    featured: false,
  },
  {
    id: 'javitri-mace',
    title: 'Javitri (Mace)',
    slug: 'javitri-mace',
    category: 'spices',
    image: '/products/spices/javitri-mace.webp',
    description: 'Whole mace blades (javitri) with a delicate, warm aroma. A signature spice in biryani, korma and premium meat preparations.',
    weight: '7oz',
    featured: false,
  },
  {
    id: 'sesame-seeds',
    title: 'Sesame Seeds (Hulled)',
    slug: 'sesame-seeds',
    category: 'spices',
    image: '/products/spices/sesame-seeds.webp',
    description: 'Hulled sesame seeds, cleaned to a uniform white grade. Suited to bakery, confectionery, tahini production and garnishing.',
    weight: '14oz',
    featured: false,
  },
  {
    id: 'vermicelli',
    title: 'Vermicelli',
    slug: 'vermicelli',
    category: 'vermicellis',
    image: '/products/vermicellis/vermicelli.webp',
    description: 'Fine wheat vermicelli, evenly drawn and dried. The base for kheer, sheer khurma and everyday sweet and savoury dishes.',
    weight: '150g',
    featured: false,
  },
  {
    id: 'pheny-fried-vermicelli',
    title: 'Pheny Fried Vermicelli',
    slug: 'pheny-fried-vermicelli',
    category: 'vermicellis',
    image: '/products/vermicellis/pheny-fried-vermicelli.webp',
    description: 'Pre-roasted pheny vermicelli, ready to cook straight from the pack. Saves preparation time for desserts and food-service kitchens.',
    weight: '180g / 6.35 oz',
    featured: true,
  },
  {
    id: 'green-tea-110g',
    title: 'Green Tea (110g)',
    slug: 'green-tea-110g',
    category: 'tea',
    image: '/products/tea/green-tea-110g.webp',
    description: 'Whole-leaf green tea with a light, clean finish. Compact pack size for everyday retail.',
    weight: '110g',
    featured: true,
  },
  {
    id: 'green-tea-250g',
    title: 'Green Tea (250g)',
    slug: 'green-tea-250g',
    category: 'tea',
    image: '/products/tea/green-tea-250g.webp',
    description: 'Whole-leaf green tea in a value pack for regular drinkers and food-service use. Brews a bright, refreshing cup.',
    weight: '250g',
    featured: false,
  },
  {
    id: 'lemongrass-tea',
    title: 'Lemon Grass Tea',
    slug: 'lemongrass-tea',
    category: 'tea',
    image: '/products/tea/lemongrass-tea.webp',
    description: 'Naturally caffeine-free lemon grass herbal infusion with a citrus aroma. Enjoyed hot or iced, on its own or blended with green tea.',
    weight: '100g',
    featured: false,
  },
  {
    id: 'pink-tea',
    title: 'Pink Tea (Kashmiri Chai)',
    slug: 'pink-tea',
    category: 'tea',
    image: '/products/tea/pink-tea.webp',
    description: 'Traditional Kashmiri pink tea (noon chai) blend that develops its signature rose colour and creamy body when brewed with milk.',
    weight: '190g',
    featured: true,
  },
  {
    id: 'honey-500g',
    title: 'Natural Honey (500g)',
    slug: 'honey-500g',
    category: 'honey',
    image: '/products/honey/honey-500g.webp',
    description: 'Pure natural honey, filtered but unheated to protect its aroma and natural enzymes. Retail jar size for grocery and gift ranges.',
    weight: '1 lb 1.64 oz / 500g',
    featured: true,
  },
  {
    id: 'honey-1kg',
    title: 'Natural Honey (1kg)',
    slug: 'honey-1kg',
    category: 'honey',
    image: '/products/honey/honey-1kg.webp',
    description: 'Pure natural honey in a family-size jar. A cost-effective format for regular households and food-service buyers.',
    weight: '2.2 lb 3.27 oz / 1kg',
    featured: false,
  },
  {
    id: 'kitchenware-set',
    title: 'Kitchenware Set',
    slug: 'kitchenware-set',
    category: 'utensils-kitchenware',
    image: '/products/utensils-kitchenware/kitchenware-set.webp',
    description: 'Practical everyday kitchenware set assembled for household use. Packing and assortment can be adjusted to buyer requirement.',
    weight: 'Assorted',
    featured: true,
  },
  {
    id: 'mortar-and-pestle',
    title: 'Mortar and Pestle',
    slug: 'mortar-and-pestle',
    category: 'utensils-kitchenware',
    image: '/products/utensils-kitchenware/mortar-and-pestle.webp',
    description: 'Traditional stone mortar and pestle for grinding whole spices, garlic and herbs. Heavy, stable and built to last.',
    weight: '—',
    featured: true,
  },
  {
    id: 'blue-pottery-vases',
    title: 'Blue Pottery Vase Set',
    slug: 'blue-pottery-vases',
    category: 'utensils-kitchenware',
    image: '/products/utensils-kitchenware/blue-pottery.webp',
    description: 'Hand-painted traditional blue pottery vases in assorted sizes. Each piece is individually decorated with classic floral motifs — a decorative and gifting favourite.',
    weight: 'Assorted',
    featured: true,
  },
  {
    id: 'ceramic-pottery-set',
    title: 'Ceramic Hand-Painted Tea Set',
    slug: 'ceramic-pottery-set',
    category: 'utensils-kitchenware',
    image: '/products/utensils-kitchenware/ceramic-pottery.webp',
    description: 'Hand-painted ceramic pottery set — teapot, cups, serving bowls and dishes finished with vivid traditional patterns. A colourful centrepiece for table and gifting ranges.',
    weight: 'Assorted',
    featured: false,
  },
  {
    id: 'rolling-pin-board',
    title: 'Rolling Pin and Board',
    slug: 'rolling-pin-board',
    category: 'utensils-kitchenware',
    image: '/products/utensils-kitchenware/rolling-pin-board.webp',
    description: 'Wooden rolling pin and board (chakla belan) for rotis, parathas and pastry. A staple in every South Asian kitchen.',
    weight: '—',
    featured: false,
  },
  {
    id: 'gas-tandoor',
    title: 'Stainless Steel Gas Tandoor',
    slug: 'gas-tandoor',
    category: 'utensils-kitchenware',
    image: '/products/utensils-kitchenware/gas-tandoor.webp',
    description: 'Stainless steel gas tandoor for baking roti and naan at home. Compact build suited to household and small food-service use.',
    weight: '—',
    featured: true,
  },
  {
    id: 'broom',
    title: 'Broom (Jharoo)',
    slug: 'broom',
    category: 'miscellanous',
    image: '/products/miscellanous/broom.webp',
    description: 'Durable household broom with a firm sweep and comfortable handle. Suitable for indoor and outdoor cleaning.',
    weight: '—',
    featured: false,
  },
  {
    id: 'washroom-lota',
    title: 'Washroom Vessel (Lota)',
    slug: 'washroom-lota',
    category: 'miscellanous',
    image: '/products/miscellanous/washroom-vessel-lota.webp',
    description: 'Traditional washroom vessel (lota) in a sturdy, easy-clean finish. A household essential across South Asia and the Gulf.',
    weight: '—',
    featured: false,
  },
  {
    id: 'charpai',
    title: 'Woven Rope Bed (Charpai)',
    slug: 'charpai',
    category: 'miscellanous',
    image: '/products/miscellanous/woven-rope-bed-charpai.webp',
    description: 'Hand-woven rope bed (charpai) built on a traditional wooden frame. A durable seating and sleeping piece with authentic craft appeal.',
    weight: '—',
    featured: false,
  },
  {
    id: 'carrom-board',
    title: 'Carrom Board',
    slug: 'carrom-board',
    category: 'miscellanous',
    image: '/products/miscellanous/carrom-board.webp',
    description: 'Classic carrom board with a smooth playing surface, supplied with coins and striker. A long-standing family favourite.',
    weight: '—',
    featured: false,
  },
  {
    id: 'ludo',
    title: 'Ludo Board',
    slug: 'ludo',
    category: 'miscellanous',
    image: '/products/miscellanous/ludo.webp',
    description: 'Traditional ludo board game for two to four players. Simple, durable and suited to all ages.',
    weight: '—',
    featured: false,
  },
  {
    id: 'mango-pickle',
    title: 'Mango Pickle (Achar)',
    slug: 'mango-pickle',
    category: 'pickle-achar',
    image: '/products/pickle-achar/mango-pickle.webp',
    description: 'Traditional mango pickle (achar) cured with mustard oil and whole spices. Sharp, tangy and matured for full flavour.',
    weight: '1kg',
    featured: true,
  },
  {
    id: 'soy-sauce',
    title: 'Soy Sauce',
    slug: 'soy-sauce',
    category: 'sauces',
    image: '/products/sauces/soy-sauce.webp',
    description: 'Rich, well-balanced soy sauce for stir-fries, marinades and dipping. Available in retail and food-service formats.',
    weight: '280ml / 9.47oz',
    featured: true,
  },
  {
    id: 'synthetic-vinegar',
    title: 'Synthetic Vinegar',
    slug: 'synthetic-vinegar',
    category: 'sauces',
    image: '/products/sauces/synthetic-vinegar.webp',
    description: 'Clear synthetic vinegar of consistent strength, for pickling, dressings and everyday kitchen use.',
    weight: '285ml / 10oz',
    featured: false,
  },
  {
    id: 'thai-chilli-sauce',
    title: 'Thai Chilli Sauce',
    slug: 'thai-chilli-sauce',
    category: 'sauces',
    image: '/products/sauces/thai-chilli-sauce.webp',
    description: 'Sweet Thai-style chilli sauce with a gentle heat and glossy finish. A versatile dip and glaze for grilled dishes.',
    weight: '300gm / 10.58oz',
    featured: true,
  },
  {
    id: 'chilli-sauce',
    title: 'Chilli Sauce',
    slug: 'chilli-sauce',
    category: 'sauces',
    image: '/products/sauces/chilli-sauce.webp',
    description: 'Classic hot chilli sauce with a clean, direct heat. Popular with snacks, fast food and food-service kitchens.',
    weight: '300gm / 10.58oz',
    featured: true,
  },
  {
    id: 'peri-peri-sauce',
    title: 'Peri Peri Sauce',
    slug: 'peri-peri-sauce',
    category: 'sauces',
    image: '/products/sauces/peri-peri-sauce.webp',
    description: 'Bold peri peri sauce with a smoky, tangy heat. Excellent as a marinade for grilled chicken or as a table sauce.',
    weight: '300gm / 10.58oz',
    featured: true,
  },
  {
    id: 'coriander-sauce',
    title: 'Coriander Sauce',
    slug: 'coriander-sauce',
    category: 'sauces',
    image: '/products/sauces/coriander-sauce.webp',
    description: 'Fresh, herby coriander sauce with a bright, zesty finish. Served with grills, samosas and street-food favourites.',
    weight: '300gm / 10.58oz',
    featured: false,
  },
  {
    id: 'fried-onion',
    title: 'Fried Onion',
    slug: 'fried-onion',
    category: 'fried-onion',
    image: '/products/fried-onion/fried-onion.webp',
    description: 'Crispy golden fried onion flakes for biryani, salads and garnishing.',
    weight: '14oz / 400gm',
    featured: true,
  },
  {
    id: 'himalayan-pink-salt',
    title: 'Himalayan Pink Salt',
    slug: 'himalayan-pink-salt',
    category: 'salts',
    image: '/products/salts/himalayan-pink-salt.webp',
    description: 'Naturally mined Himalayan pink salt, unrefined and rich in trace minerals. Table-size pack for everyday cooking and seasoning.',
    weight: '26.45 oz / 750gm',
    featured: true,
  },
  {
    id: 'himalayan-fine-pink-salt',
    title: 'Himalayan Fine Pink Salt (Jar)',
    slug: 'himalayan-fine-pink-salt',
    category: 'salts',
    image: '/products/salts/himalayan-fine-pink-salt.webp',
    description: 'Finely ground Himalayan pink salt in a sealed jar, ready for table and shaker use. Clean, mild salinity with a subtle mineral note.',
    weight: '13.05 oz / 370gm',
    featured: true,
  },
  {
    id: 'far-far-circle',
    title: 'Far Far Circle Fryum',
    slug: 'far-far-circle',
    category: 'snacks',
    image: '/products/snacks/far-far-circle.webp',
    description: 'Colourful circle fryum pellets that puff up crisp in seconds. Supplied uncooked for long shelf life and easy preparation.',
    weight: '14oz / 400gm',
    featured: true,
  },
  {
    id: 'far-far-star',
    title: 'Far Far Star Fryum',
    slug: 'far-far-star',
    category: 'snacks',
    image: '/products/snacks/far-far-star.webp',
    description: 'Star-shaped fryum pellets that fry up light and crunchy. A colourful favourite with children and party platters.',
    weight: '14oz / 400gm',
    featured: false,
  },
  {
    id: 'far-far-okra',
    title: 'Far Far Okra Fryum',
    slug: 'far-far-okra',
    category: 'snacks',
    image: '/products/snacks/far-far-okra.webp',
    description: 'Okra-shaped fryum pellets, crisp and airy once fried. A traditional accompaniment to South Asian meals.',
    weight: '14oz / 400gm',
    featured: false,
  },
  {
    id: 'far-far-pipe-colour',
    title: 'Far Far Pipe Fryum (Colour)',
    slug: 'far-far-pipe-colour',
    category: 'snacks',
    image: '/products/snacks/far-far-pipe-colour.webp',
    description: 'Multi-coloured pipe-shaped fryum pellets with an appealing shelf presence. Fries quickly to a light crunch.',
    weight: '14oz / 400gm',
    featured: false,
  },
  {
    id: 'far-far-pipe-yellow',
    title: 'Far Far Pipe Fryum (Yellow)',
    slug: 'far-far-pipe-yellow',
    category: 'snacks',
    image: '/products/snacks/far-far-pipe-yellow.webp',
    description: 'Yellow pipe-shaped fryum pellets, crisp and light. A classic everyday snack format.',
    weight: '14oz / 400gm',
    featured: false,
  },
  {
    id: 'lahori-nimko-mix-jar',
    title: 'Lahori Nimko Mix (Jar)',
    slug: 'lahori-nimko-mix-jar',
    category: 'snacks',
    image: '/products/snacks/lahori-nimko-mix-jar.webp',
    description: 'Classic Lahori nimko mix of gram flour noodles, lentils, nuts and spice, in a resealable jar. Balanced heat with a savoury finish.',
    weight: '14oz / 400gm',
    featured: true,
  },
  {
    id: 'bhujia-seve',
    title: 'Bhujia Seve Namkeen',
    slug: 'bhujia-seve',
    category: 'snacks',
    image: '/products/snacks/bhujia-seve.webp',
    description: 'Fine, crunchy gram-flour bhujia seve with a gentle spice. The everyday tea-time namkeen across South Asia.',
    weight: '14oz / 400gm',
    featured: false,
  },
  {
    id: 'hot-mix',
    title: 'Hot Mix Namkeen',
    slug: 'hot-mix',
    category: 'snacks',
    image: '/products/snacks/hot-mix.webp',
    description: 'Spicy hot mix namkeen combining crisp noodles, lentils and peanuts. A bold blend for buyers who want real heat.',
    weight: '14oz / 400gm',
    featured: false,
  },
  {
    id: 'lahori-nimko',
    title: 'Lahori Nimko Namkeen',
    slug: 'lahori-nimko',
    category: 'snacks',
    image: '/products/snacks/lahori-nimko.webp',
    description: 'Traditional Lahori nimko blend, seasoned the authentic way. Crisp, savoury and well suited to gifting packs.',
    weight: '14oz / 400gm',
    featured: false,
  },
  {
    id: 'moong-daal',
    title: 'Moong Daal Namkeen',
    slug: 'moong-daal',
    category: 'snacks',
    image: '/products/snacks/moong-daal.webp',
    description: 'Crisp fried moong daal, lightly salted and evenly cooked. A simple, protein-rich namkeen with wide appeal.',
    weight: '14oz / 400gm',
    featured: false,
  },
  {
    id: 'roasted-gram-jar',
    title: 'Roasted Gram (Jar)',
    slug: 'roasted-gram-jar',
    category: 'snacks',
    image: '/products/snacks/roasted-gram-jar.webp',
    description: 'Wholesome roasted gram (chana) with the skin retained, in a resealable jar. A high-protein, oil-free everyday snack.',
    weight: '14oz / 400gm',
    featured: false,
  },
  {
    id: 'roasted-gram-without-skin',
    title: 'Roasted Gram Without Skin (Jar)',
    slug: 'roasted-gram-without-skin',
    category: 'snacks',
    image: '/products/snacks/roasted-gram-without-skin.webp',
    description: 'Skinless roasted gram, smooth textured and easy to eat. Also used in chutneys and traditional sweets.',
    weight: '14oz / 400gm',
    featured: false,
  },
  {
    id: 'roasted-salted-corn',
    title: 'Roasted Salted Corn (Jar)',
    slug: 'roasted-salted-corn',
    category: 'snacks',
    image: '/products/snacks/roasted-salted-corn.webp',
    description: 'Crunchy roasted corn kernels with a clean salted finish. A light, oil-free snack for jars and shelf packs.',
    weight: '14oz / 400gm',
    featured: false,
  },
  {
    id: 'roasted-sweet-corn',
    title: 'Roasted Sweet Corn (Jar)',
    slug: 'roasted-sweet-corn',
    category: 'snacks',
    image: '/products/snacks/roasted-sweet-corn.webp',
    description: 'Roasted corn kernels with a gentle sweetness balancing the crunch. Popular across snacking and gifting ranges.',
    weight: '14oz / 400gm',
    featured: false,
  },
  {
    id: 'chakwali-rewri',
    title: 'Chakwali Rewri',
    slug: 'chakwali-rewri',
    category: 'snacks',
    image: '/products/snacks/chakwali-rewri.webp',
    description: 'Traditional Chakwal-style rewri — sesame seeds bound in crisp jaggery. A winter favourite with authentic regional character.',
    weight: '14oz / 400gm',
    featured: true,
  },
  {
    id: 'sweet-makhana',
    title: 'Sweet Makhana',
    slug: 'sweet-makhana',
    category: 'snacks',
    image: '/products/snacks/sweet-makhana.webp',
    description: 'Lightly sweetened fox nuts (makhana), roasted to an airy crunch. A naturally gluten-free, low-oil snack.',
    weight: '10.58 oz / 300gm',
    featured: true,
  },
  {
    id: 'namak-para',
    title: 'Namak Para (Crispy & Creamy)',
    slug: 'namak-para',
    category: 'snacks',
    image: '/products/snacks/namak-para.webp',
    description: 'Traditional crispy namak para — light, flaky savoury bites with a creamy, buttery crunch. A classic tea-time snack.',
    weight: '180 g / 6.35 oz',
    featured: true,
  },
  {
    id: 'lahori-dahi-pakori',
    title: 'Lahori Dahi Pakori (Crispy & Creamy)',
    slug: 'lahori-dahi-pakori',
    category: 'snacks',
    image: '/products/snacks/lahori-dahi-pakori.webp',
    description: 'Lahori-style dahi pakori — crisp gram-flour pakoris ready for soaking in yoghurt. Crispy outside, creamy once dressed.',
    weight: '200 g / 7 oz',
    featured: true,
  },
  {
    id: 'lahori-dahi-phulki',
    title: 'Lahori Dahi Phulki (Crispy & Creamy)',
    slug: 'lahori-dahi-phulki',
    category: 'snacks',
    image: '/products/snacks/lahori-dahi-phulki.webp',
    description: 'Lahori-style dahi phulki — small, light gram-flour puffs for dahi bhalla and raita. Crispy dry, soft and creamy when soaked.',
    weight: '200 g / 7 oz',
    featured: false,
  },
  {
    id: 'char-gond',
    title: 'Char Gond',
    slug: 'char-gond',
    category: 'edible-gums-and-resins',
    image: '/products/edible-gums-and-resins/char-gond.webp',
    description: 'Natural edible gum (char gond), traditionally used in winter sweets, laddus and strengthening preparations.',
    weight: '3.5 oz / 100gm',
    featured: true,
  },
  {
    id: 'gond-katira',
    title: 'Gond Katira',
    slug: 'gond-katira',
    category: 'edible-gums-and-resins',
    image: '/products/edible-gums-and-resins/gond-katira.webp',
    description: 'Gond katira (tragacanth gum), a natural cooling resin that swells in water. Widely used in summer drinks and traditional remedies.',
    weight: '3.5 oz / 100gm',
    featured: true,
  },
  {
    id: 'dry-date-dark-400g',
    title: 'Dry Date Dark',
    slug: 'dry-date-dark-400g',
    category: 'dry-fruits-packing',
    image: '/products/dry-fruits-packing/dry-date-dark-400g.webp',
    description: 'Dark-variety dried dates with a deeper caramel note and firmer bite. Available in 200 g and 400 g retail packs — custom packing also made to order.',
    weight: '200 g & 400 g',
    featured: false,
  },
  {
    id: 'dry-date-light-400g',
    title: 'Dry Date Light',
    slug: 'dry-date-light-400g',
    category: 'dry-fruits-packing',
    image: '/products/dry-fruits-packing/dry-date-light-400g.webp',
    description: 'Light-variety dried dates, milder and softer than the dark grade. Available in 200 g and 400 g retail packs — custom packing also made to order.',
    weight: '200 g & 400 g',
    featured: false,
  },
  {
    id: 'bulk-dry-munakka',
    title: 'Dry Munakka (Bulk)',
    slug: 'bulk-dry-munakka',
    category: 'dry-fruits-bulk',
    image: '/products/dry-fruits-bulk/bulk-dry-munakka.webp',
    description: 'Dried munakka supplied in bulk quantities for wholesale and processing buyers. Every packing option available — send an enquiry for grades and pricing.',
    weight: 'Bulk / Custom packing',
    featured: false,
  },
  {
    id: 'bulk-dry-plum',
    title: 'Dry Plum / Aloo Bukhara (Bulk)',
    slug: 'bulk-dry-plum',
    category: 'dry-fruits-bulk',
    image: '/products/dry-fruits-bulk/bulk-dry-plum.webp',
    description: 'Dried plums (aloo bukhara) supplied loose in bulk. Available in cartons, sacks or private-label packing. Send an enquiry for grades, sizes and pricing.',
    weight: 'Bulk / Custom packing',
    featured: false,
  },
  {
    id: 'bulk-dry-dates',
    title: 'Light Dry Dates (Bulk)',
    slug: 'bulk-dry-dates',
    category: 'dry-fruits-bulk',
    image: '/products/dry-fruits-bulk/bulk-dry-dates.webp',
    description: 'Light-variety dried dates (chuara) supplied in bulk for repackers, food manufacturers and wholesalers. Packing to your specification — send an enquiry for grades and pricing.',
    weight: 'Bulk / Custom packing',
    featured: false,
  },
  {
    id: 'bulk-dry-dates-dark',
    title: 'Dark Dry Dates (Bulk)',
    slug: 'bulk-dry-dates-dark',
    category: 'dry-fruits-bulk',
    image: '/products/dry-fruits-bulk/bulk-dry-dates-dark.webp',
    description: 'Dark-variety dried dates supplied loose in bulk, with a deeper colour and firmer bite. Packing to your specification — send an enquiry for grades and pricing.',
    weight: 'Bulk / Custom packing',
    featured: false,
  },
  {
    id: 'bulk-golden-raisin',
    title: 'Golden Raisin (Bulk)',
    slug: 'bulk-golden-raisin',
    category: 'dry-fruits-bulk',
    image: '/products/dry-fruits-bulk/bulk-golden-raisin.webp',
    description: 'Golden raisins supplied loose in bulk for processors, packers and distributors. Packing made to your specification — send an enquiry for grades and pricing.',
    weight: 'Bulk / Custom packing',
    featured: false,
  },
  {
    id: 'bulk-dry-raisin',
    title: 'Black Dry Raisin (Bulk)',
    slug: 'bulk-dry-raisin',
    category: 'dry-fruits-bulk',
    image: '/products/dry-fruits-bulk/bulk-dry-raisin.webp',
    description: 'Dried black raisins supplied in bulk quantities for industrial and repacking buyers. Every packing format available — send an enquiry for grades, sizes and pricing.',
    weight: 'Bulk / Custom packing',
    featured: false,
  },
  {
    id: 'bulk-dry-fig',
    title: 'Dry Fig / Anjeer (Bulk)',
    slug: 'bulk-dry-fig',
    category: 'dry-fruits-bulk',
    image: '/products/dry-fruits-bulk/bulk-dry-fig.webp',
    description: 'Whole dried figs (anjeer) supplied loose in bulk. Graded to requirement and packed in cartons, sacks or private label. Send an enquiry for details.',
    weight: 'Bulk / Custom packing',
    featured: false,
  },
  {
    id: 'himalayan-pink-salt-5lb',
    title: 'Himalayan Pink Salt',
    slug: 'himalayan-pink-salt-5lb',
    category: 'salts',
    image: '/products/salts/himalayan-pink-salt-5lb.webp',
    description: 'Naturally mined Himalayan pink salt in a large catering pack. Sized for restaurants, food processors and bulk retail buyers.',
    weight: '5 lb / 2268 gm',
    featured: false,
  },
  {
    id: 'himalayan-rock-pink-salt-1kg',
    title: 'Himalayan Pink Salt Rock',
    slug: 'himalayan-rock-pink-salt-1kg',
    category: 'salts',
    image: '/products/salts/himalayan-rock-pink-salt-1kg.webp',
    description: 'Himalayan pink rock salt crystals in a one-kilo pack. Suited to grinders, curing, and specialty retail ranges.',
    weight: '1 kg',
    featured: false,
  },
  {
    id: 'black-fine-salt',
    title: 'Black Fine Salt (Kala Namak)',
    slug: 'black-fine-salt',
    category: 'salts',
    image: '/products/salts/black-fine-salt.webp',
    description: 'Finely ground black salt (kala namak) with its distinctive sulphurous, savoury character. Essential to chaat, raita and salad seasonings.',
    weight: '14 oz / 400gm',
    featured: false,
  },
  {
    id: 'black-salt-fine-200g',
    title: 'Black Salt Fine',
    slug: 'black-salt-fine-200g',
    category: 'salts',
    image: '/products/salts/black-salt-fine-200g.webp',
    description: 'Finely ground black salt (kala namak) in a compact 200 g retail pack. The classic sulphurous, savoury note for chaat, raita and salad seasonings.',
    weight: '7 oz / 200gm',
    featured: false,
  },
  {
    id: 'rasgulla-1kg',
    title: 'Rasgulla (Canned)',
    slug: 'rasgulla-1kg',
    category: 'sweets-and-confectionery',
    image: '/products/sweets-and-confectionery/rasgulla-1kg.webp',
    description: 'Soft cottage-cheese dumplings in light sugar syrup, canned to hold their texture. Ready to serve chilled straight from the tin.',
    weight: '1 kg / 35.27 oz',
    featured: true,
  },
  {
    id: 'gulab-jamun-1kg',
    title: 'Gulab Jamun (Canned)',
    slug: 'gulab-jamun-1kg',
    category: 'sweets-and-confectionery',
    image: '/products/sweets-and-confectionery/gulab-jamun-1kg.webp',
    description: 'Classic gulab jamun in fragrant sugar syrup, canned for a long ambient shelf life. Serve warm or chilled, no preparation needed.',
    weight: '1 kg / 35.27 oz',
    featured: true,
  },
  {
    id: 'chum-chum-1kg',
    title: 'Chum Chum (Canned)',
    slug: 'chum-chum-1kg',
    category: 'sweets-and-confectionery',
    image: '/products/sweets-and-confectionery/chum-chum-1kg.webp',
    description: 'Traditional chum chum in sugar syrup, canned to retain its soft, spongy bite. A festive favourite ready to plate.',
    weight: '1 kg / 35.27 oz',
    featured: false,
  },
  {
    id: 'murabba-ashrafi-green',
    title: 'Murabba Ashrafi (Green)',
    slug: 'murabba-ashrafi-green',
    category: 'sweets-and-confectionery',
    image: '/products/sweets-and-confectionery/murabba-ashrafi-green.webp',
    description: 'Traditional ashrafi murabba in the green variety — fruit preserved slowly in sugar syrup until tender and glossy.',
    weight: '14.11 oz / 400 gm',
    featured: false,
  },
  {
    id: 'murabba-ashrafi-red',
    title: 'Murabba Ashrafi (Red)',
    slug: 'murabba-ashrafi-red',
    category: 'sweets-and-confectionery',
    image: '/products/sweets-and-confectionery/murabba-ashrafi-red.webp',
    description: 'Traditional ashrafi murabba in the red variety, slow-cooked in sugar syrup for a rich colour and deep, sweet flavour.',
    weight: '14.11 oz / 400 gm',
    featured: false,
  },
  {
    id: 'nutmeg-jaifal',
    title: 'Nutmeg Whole (Jaifal)',
    slug: 'nutmeg-jaifal',
    category: 'spices',
    image: '/products/spices/nutmeg-jaifal.webp',
    description: 'Whole nutmeg (jaifal), hand-sorted and packed to retain its warm, sweet aroma. Grated fresh for curries, desserts and spice blends.',
    weight: '3.5 oz / 100 gm',
    featured: false,
  },
  {
    id: 'soap-nut-areetha',
    title: 'Soap Nut Whole (Areetha)',
    slug: 'soap-nut-areetha',
    category: 'spices',
    image: '/products/spices/soap-nut-areetha.webp',
    description: 'Whole soap nuts (areetha), naturally rich in saponins. A traditional botanical used in herbal hair care and natural cleaning preparations.',
    weight: '3.5 oz / 100 gm',
    featured: false,
  },
  {
    id: 'chia-seeds',
    title: 'Chia Seeds',
    slug: 'chia-seeds',
    category: 'edible-gums-and-resins',
    image: '/products/edible-gums-and-resins/chia-seeds.webp',
    description: 'Premium chia seeds, cleaned and graded to a uniform quality. High in fibre and omega-3, used in drinks, puddings, bakery and health foods.',
    weight: '100 gm',
    featured: false,
  },
  {
    id: 'tukmaria-basil-seeds',
    title: 'Tukmaria (Basil Seeds)',
    slug: 'tukmaria-basil-seeds',
    category: 'edible-gums-and-resins',
    image: '/products/edible-gums-and-resins/tukmaria-basil-seeds.webp',
    description: 'Tukmaria (sweet basil seeds), cleaned and sorted. Swell into a soft gel in water — a classic ingredient in falooda and summer coolers.',
    weight: '100 gm',
    featured: false,
  },
  {
    id: 'chanachur-mix-extra-hot',
    title: 'Chanachur Mix Extra Hot',
    slug: 'chanachur-mix-extra-hot',
    category: 'snacks',
    image: '/products/snacks/chanachur-mix-extra-hot.webp',
    description: 'Extra-hot chanachur namkeen mix with a sharp chilli finish. Built for buyers whose customers want maximum heat.',
    weight: '100 gm',
    featured: false,
  },
  {
    id: 'punjabi-sarson-saag',
    title: 'Punjabi Sarson Saag',
    slug: 'punjabi-sarson-saag',
    category: 'exclusive-products-saag-halwa',
    image: '/products/exclusive-products-saag-halwa/punjabi-sarson-saag.webp',
    description: 'Authentic Punjabi sarson saag — mustard leaves slow-cooked with traditional spices. Simply heat and serve with makai roti.',
    weight: '800 g / 28.2 oz',
    featured: true,
  },
  {
    id: 'namal-desi-ghee',
    title: 'Namal Desi Ghee',
    slug: 'namal-desi-ghee',
    category: 'desi-ghee',
    image: '/products/desi-ghee/namal-desi-ghee.webp',
    description: 'Pure Namal desi ghee (clarified butter) with a rich aroma and golden colour. Available in two sizes — 500 g and 1 kg jars.',
    weight: '500 g & 1 kg',
    featured: true,
  },
  {
    id: 'multani-sohan-halwa-14oz',
    title: 'Multani Sohan Halwa',
    slug: 'multani-sohan-halwa-14oz',
    category: 'sweets-and-confectionery',
    image: '/products/sweets-and-confectionery/multani-sohan-halwa-14oz.webp',
    description: 'Traditional Multani sohan halwa, cooked slowly with ghee, nuts and cardamom until dense and rich. A celebrated regional speciality.',
    weight: '14 oz / 400 gm',
    featured: true,
  },
  {
    id: 'multani-sohan-halwa-45g',
    title: 'Multani Sohan Halwa (Single)',
    slug: 'multani-sohan-halwa-45g',
    category: 'sweets-and-confectionery',
    image: '/products/sweets-and-confectionery/multani-sohan-halwa-45g.webp',
    description: 'Multani sohan halwa in a single-serve pack — convenient for gifting, hospitality trays and impulse retail.',
    weight: '45 g (+- 2 g)',
    featured: false,
  },
  {
    id: 'fruit-drink-2litre',
    title: 'Fruit Drink 2 Litre',
    slug: 'fruit-drink-2litre',
    category: 'drinks-and-juices',
    image: '/products/drinks-and-juices/fruit-drink-2litre.webp',
    description: 'Family-size 2 litre fruit drink in a resealable PET bottle. Available flavours: Chaunsa Mango, Guava, Lychee, Mix Fruit, Pink Guava and Pomegranate.',
    weight: '2 Litre / 68 fl oz',
    featured: true,
  },
  {
    id: 'fruit-drink-3litre',
    title: 'Fruit Drink 3 Litre',
    slug: 'fruit-drink-3litre',
    category: 'drinks-and-juices',
    image: '/products/drinks-and-juices/fruit-drink-3litre.webp',
    description: 'Value 3 litre fruit drink in a resealable PET bottle, sized for households and catering. Available flavours: Chaunsa Mango, Guava, Lychee, Mix Fruit, Pink Guava and Pomegranate.',
    weight: '3 Litre / 101 fl oz',
    featured: true,
  },
  {
    id: 'mango-chaunsa-1-5litre',
    title: 'Chaunsa Mango Fruit Drink',
    slug: 'mango-chaunsa-1-5litre',
    category: 'drinks-and-juices',
    image: '/products/drinks-and-juices/mango-chaunsa-1-5litre.webp',
    description: 'Chaunsa mango fruit drink in a 1.5 litre bottle, made from Pakistan\'s premium Chaunsa variety for a full, sweet mango character.',
    weight: '1.5 Litre / 50.72 fl oz',
    featured: false,
  },
  {
    id: 'mango-juice-250ml-bottle',
    title: 'Mango Juice Bottle',
    slug: 'mango-juice-250ml-bottle',
    category: 'drinks-and-juices',
    image: '/products/drinks-and-juices/mango-juice-250ml-bottle.webp',
    description: 'Chaunsa mango juice in a single-serve 250 ml bottle. Convenient for retail chillers, hospitality and on-the-go sales.',
    weight: '250 ml',
    featured: false,
  },
  {
    id: 'drinks-250ml-glass',
    title: 'Drinks 250 ml Glass Packing',
    slug: 'drinks-250ml-glass',
    category: 'drinks-and-juices',
    image: '/products/drinks-and-juices/drinks-250ml-glass.webp',
    description: 'Fruit drinks in 250 ml glass bottles — a premium presentation for hotels, restaurants and gifting. Flavour selection available on request.',
    weight: '250 ml (glass)',
    featured: false,
  },
  {
    id: 'mango-juice-tetra-200ml',
    title: 'Mango Juice Tetra Pack',
    slug: 'mango-juice-tetra-200ml',
    category: 'drinks-and-juices',
    image: '/products/drinks-and-juices/mango-juice-tetra-200ml.webp',
    description: 'Chaunsa mango juice in a 200 ml tetra pack. Ambient-stable, lightweight and ideal for lunchboxes, airlines and institutional supply.',
    weight: '200 ml',
    featured: false,
  },
  {
    id: 'rose-water-265ml',
    title: 'Natural Rose Water',
    slug: 'rose-water-265ml',
    category: 'arqiyaat',
    image: '/products/arqiyaat/rose-water.webp',
    description: 'Natural rose water (arq gulab), steam-distilled from fresh rose petals for a clean, delicate floral aroma. Used in desserts, drinks, and traditional wellness preparations.',
    weight: '265 ml',
    featured: true,
  },
  {
    id: 'kewra-water-265ml',
    title: 'Natural Kewra Water',
    slug: 'kewra-water-265ml',
    category: 'arqiyaat',
    image: '/products/arqiyaat/kewra-water.webp',
    description: 'Natural kewra water (arq kewra), distilled from pandanus flowers. A signature aroma in biryani, sweets and traditional drinks across South Asia and the Gulf.',
    weight: '265 ml',
    featured: true,
  },
]

export function getCategory(slug) {
  return categories.find(c => c.slug === slug) || null
}

export function getProductsByCategory(slug) {
  const category = getCategory(slug)
  return products.filter(p => p.category === slug || p.category === category?.id)
}

export function getProduct(slug) {
  return products.find(p => p.slug === slug) || null
}
