export const categories = [
  { id: 'drinks-and-juices', title: 'Drink and Juices', slug: 'drinks-and-juices', accent: '#D97706', description: 'Refreshing juices and drinks' },
  { id: 'bulk-dry-fruits-nuts', title: 'Bulk Dry Fruits/Nuts', slug: 'bulk-dry-fruits-nuts', accent: '#8B5A2B', description: 'Premium dry fruits and nuts' },
  { id: 'spices', title: 'Spices', slug: 'spices', accent: '#B91C1C', description: 'Aromatic spices and blends' },
  { id: 'vermicellis', title: 'Vermicelli', slug: 'vermicellis', accent: '#C7A24A', description: 'Quality vermicelli products' },
  { id: 'tea', title: 'Tea', slug: 'tea', accent: '#31572C', description: 'Everyday and premium tea' },
  { id: 'snacks', title: 'Snacks', slug: 'snacks', accent: '#D97706', description: 'Tasty snacks and nimko' },
  { id: 'honey', title: 'Honey', slug: 'honey', accent: '#F5C518', description: 'Natural honey products' },
  { id: 'arqiyaat', title: 'Arqiyaat', slug: 'arqiyaat', accent: '#4A8B1F', description: 'Traditional arqiyaat range' },
  { id: 'miscellanous', title: 'Miscellaneous', slug: 'miscellanous', accent: '#2D5016', description: 'Miscellaneous food items' },
  { id: 'exclusive-products-saag-halwa', title: 'Exclusive Products Saag/Halwa', slug: 'exclusive-products-saag-halwa', accent: '#6B3F1D', description: 'Exclusive traditional products' },
  { id: 'utensils-kitchenware', title: 'Utensils & Kitchenware', slug: 'utensils-kitchenware', accent: '#1F2937', description: 'Kitchenware and utensils' },
  { id: 'pickle-achar', title: 'Pickle/Achar', slug: 'pickle-achar', accent: '#7F1D1D', description: 'Pickles and achar' },
  { id: 'sauces', title: 'Sauces', slug: 'sauces', accent: '#D97706', description: 'Sauces and condiments' },
  { id: 'fried-onion', title: 'Fried Onion', slug: 'fried-onion', accent: '#C7842B', description: 'Crispy fried onion flakes' },
  { id: 'himalayan-pink-salt', title: 'Himalayan Pink Salt', slug: 'himalayan-pink-salt', accent: '#E8A0A0', description: 'Pure Himalayan pink salt' },
]

export const products = [
  {
    id: 'mango-juice',
    title: 'Mango Juice',
    slug: 'mango-juice',
    category: 'drinks-and-juices',
    image: null,
    description: 'Refreshing mango juice for local and export buyers.',
    weight: '3 Liter',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'mixed-nuts',
    title: 'Mixed Nuts',
    slug: 'mixed-nuts',
    category: 'bulk-dry-fruits-nuts',
    image: null,
    description: 'Hand-picked assorted nuts blend.',
    weight: '750g',
    origin: 'Various',
    featured: true,
  },
  {
    id: 'red-chilli-powder',
    title: 'Red Chilli Powder',
    slug: 'red-chilli-powder',
    category: 'spices',
    image: null,
    description: 'Rich color and aroma for food service and retail packs.',
    weight: '200g',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'roasted-vermicelli',
    title: 'Roasted Vermicelli',
    slug: 'roasted-vermicelli',
    category: 'vermicellis',
    image: null,
    description: 'Fine roasted vermicelli for desserts and everyday use.',
    weight: '150g',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'black-tea',
    title: 'Black Tea',
    slug: 'black-tea',
    category: 'tea',
    image: null,
    description: 'Strong everyday tea with reliable packing quality.',
    weight: '250g',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'nimko-mix',
    title: 'Nimko Mix',
    slug: 'nimko-mix',
    category: 'snacks',
    image: null,
    description: 'Crispy Pakistani snack mix with balanced spice.',
    weight: '200g',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'natural-honey',
    title: 'Natural Honey',
    slug: 'natural-honey',
    category: 'honey',
    image: null,
    description: 'Smooth natural honey packed for retail and export.',
    weight: '500g',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'rose-arq',
    title: 'Rose Arq',
    slug: 'rose-arq',
    category: 'arqiyaat',
    image: null,
    description: 'Traditional rose arq with clean aroma and taste.',
    weight: '800ml',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'food-essentials',
    title: 'Food Essentials',
    slug: 'food-essentials',
    category: 'miscellanous',
    image: null,
    description: 'Selected grocery essentials for varied buyer needs.',
    weight: 'Assorted',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'saag-halwa-pack',
    title: 'Saag/Halwa Pack',
    slug: 'saag-halwa-pack',
    category: 'exclusive-products-saag-halwa',
    image: null,
    description: 'Exclusive traditional food range for seasonal demand.',
    weight: '1kg',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'kitchenware-set',
    title: 'Kitchenware Set',
    slug: 'kitchenware-set',
    category: 'utensils-kitchenware',
    image: null,
    description: 'Useful kitchenware items for daily household needs.',
    weight: 'Assorted',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'mixed-pickle',
    title: 'Mixed Pickle',
    slug: 'mixed-pickle',
    category: 'pickle-achar',
    image: null,
    description: 'Tangy mixed achar with traditional flavor.',
    weight: '400g',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'chilli-garlic-sauce',
    title: 'Chilli Garlic Sauce',
    slug: 'chilli-garlic-sauce',
    category: 'sauces',
    image: null,
    description: 'Bold sauce for snacks, meals and food service use.',
    weight: '300g',
    origin: 'Pakistan',
    featured: false,
  },
]

export function getCategory(slug) {
  return categories.find(c => c.slug === slug) || null
}

export function getProductsByCategory(slug) {
  const category = getCategory(slug)
  return products.filter(p => p.category === slug || p.category === category?.id)
}

export function getProduct(slug) {
  return products.find(p => p.slug === slug) || null
}
