export const categories = [
  { id: 'drinks-and-juices', title: 'Drink and Juices', slug: 'drinks-and-juices', accent: '#D97706', description: 'Refreshing juices and drinks' },
  { id: 'bulk-dry-fruits-nuts', title: 'Bulk Dry Fruits/Nuts', slug: 'bulk-dry-fruits-nuts', accent: '#8B5A2B', description: 'Premium dry fruits and nuts' },
  { id: 'spices', title: 'Spices', slug: 'spices', accent: '#B91C1C', description: 'Aromatic spices and blends' },
  { id: 'vermicellis', title: 'Vermicelli', slug: 'vermicellis', accent: '#C7A24A', description: 'Quality vermicelli products' },
  { id: 'tea', title: 'Tea', slug: 'tea', accent: '#31572C', description: 'Everyday and premium tea' },
  { id: 'snacks', title: 'Snacks', slug: 'snacks', accent: '#D97706', description: 'Tasty snacks and nimko' },
  { id: 'honey', title: 'Honey', slug: 'honey', accent: '#F5C518', description: 'Natural honey products' },
  { id: 'arqiyaat', title: 'Arqiyaat', slug: 'arqiyaat', accent: '#4A8B1F', description: 'Traditional arqiyaat range' },
  { id: 'miscellanous', title: 'Miscellaneous', slug: 'miscellanous', accent: '#2D5016', description: 'Miscellaneous food items' },
  { id: 'exclusive-products-saag-halwa', title: 'Exclusive Products Saag/Halwa', slug: 'exclusive-products-saag-halwa', accent: '#6B3F1D', description: 'Exclusive traditional products' },
  { id: 'utensils-kitchenware', title: 'Utensils & Kitchenware', slug: 'utensils-kitchenware', accent: '#1F2937', description: 'Kitchenware and utensils' },
  { id: 'pickle-achar', title: 'Pickle/Achar', slug: 'pickle-achar', accent: '#7F1D1D', description: 'Pickles and achar' },
  { id: 'sauces', title: 'Sauces', slug: 'sauces', accent: '#D97706', description: 'Sauces and condiments' },
  { id: 'fried-onion', title: 'Fried Onion', slug: 'fried-onion', accent: '#C7842B', description: 'Crispy fried onion flakes' },
  { id: 'himalayan-pink-salt', title: 'Himalayan Pink Salt', slug: 'himalayan-pink-salt', accent: '#E8A0A0', description: 'Pure Himalayan pink salt' },
]

export const products = [
  {
    id: 'mango-juice',
    title: 'Mango Juice',
    slug: 'mango-juice',
    category: 'drinks-and-juices',
    image: null,
    description: 'Refreshing mango juice for local and export buyers.',
    weight: '3 Liter',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'black-mulberry',
    title: 'Black Mulberry',
    slug: 'black-mulberry',
    category: 'bulk-dry-fruits-nuts',
    image: '/products/bulk-dry-fruits-nuts/black-mulberry.jpg',
    description: 'Naturally dried black mulberries, packed for retail and export.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'white-mulberry',
    title: 'White Mulberry',
    slug: 'white-mulberry',
    category: 'bulk-dry-fruits-nuts',
    image: '/products/bulk-dry-fruits-nuts/white-mulberry.jpg',
    description: 'Sweet sun-dried white mulberries in export-ready packing.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'golden-raisin',
    title: 'Golden Raisin',
    slug: 'golden-raisin',
    category: 'bulk-dry-fruits-nuts',
    image: '/products/bulk-dry-fruits-nuts/golden-raisin.jpg',
    description: 'Premium golden raisins with a soft texture and natural sweetness.',
    weight: '7oz / 200gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'dry-plum',
    title: 'Dry Plum (Aloo Bukhara)',
    slug: 'dry-plum',
    category: 'bulk-dry-fruits-nuts',
    image: '/products/bulk-dry-fruits-nuts/dry-plum.jpg',
    description: 'Tangy dried plums, ideal for cooking and everyday snacking.',
    weight: '7oz / 200gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'black-seeds-kalonji',
    title: 'Black Seeds (Kalonji)',
    slug: 'black-seeds-kalonji',
    category: 'spices',
    image: '/products/spices/black-seeds-kalonji.png',
    description: 'Premium quality Kalonji (Nigella Seeds) in a 14oz standup pouch. Rich in flavor and widely used in South Asian cooking.',
    weight: '14oz',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'cinnamon-flat-sticks',
    title: 'Cinnamon Flat Sticks',
    slug: 'cinnamon-flat-sticks',
    category: 'spices',
    image: '/products/spices/cinnamon-flat-sticks.png',
    description: 'Aromatic flat cinnamon sticks in a 7oz pack. Perfect for curries, rice dishes and tea.',
    weight: '7oz',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'cinnamon-round-sticks',
    title: 'Cinnamon Round Sticks',
    slug: 'cinnamon-round-sticks',
    category: 'spices',
    image: '/products/spices/cinnamon-round-sticks.png',
    description: 'Premium round cinnamon sticks in a 7oz jar. Ideal for desserts, beverages and cooking.',
    weight: '7oz',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'cumin-seeds-jar',
    title: 'Cumin Seeds (Jar)',
    slug: 'cumin-seeds-jar',
    category: 'spices',
    image: '/products/spices/cumin-seeds-jar.png',
    description: 'Whole cumin seeds packed in a 14oz jar. Essential spice for everyday Pakistani and Indian cuisine.',
    weight: '14oz',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'cumin-seeds-pouch',
    title: 'Cumin Seeds (Pouch)',
    slug: 'cumin-seeds-pouch',
    category: 'spices',
    image: '/products/spices/cumin-seeds-pouch.png',
    description: 'Whole cumin seeds in a 14oz standup pouch. Convenient resealable packaging for bulk buyers.',
    weight: '14oz',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'fennel-seeds',
    title: 'Fennel Seeds (Saunf)',
    slug: 'fennel-seeds',
    category: 'spices',
    image: '/products/spices/fennel-seeds.png',
    description: 'Sweet and aromatic fennel seeds. Used in cooking, mouth freshener and traditional remedies.',
    weight: '14oz',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'javitri-mace',
    title: 'Javitri (Mace)',
    slug: 'javitri-mace',
    category: 'spices',
    image: '/products/spices/javitri-mace.png',
    description: 'Premium quality Javitri (Mace) with rich aroma. A key spice in biryanis and meat dishes.',
    weight: '7oz',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'sesame-seeds',
    title: 'Sesame Seeds (Hulled)',
    slug: 'sesame-seeds',
    category: 'spices',
    image: '/products/spices/sesame-seeds.png',
    description: 'Clean hulled sesame seeds for baking, cooking and garnishing. Export-quality packaging.',
    weight: '14oz',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'vermicelli',
    title: 'Vermicelli',
    slug: 'vermicelli',
    category: 'vermicellis',
    image: '/products/vermicellis/vermicelli.png',
    description: 'Fine quality vermicelli for desserts, kheer and everyday use.',
    weight: '150g',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'green-tea-110g',
    title: 'Green Tea (110g)',
    slug: 'green-tea-110g',
    category: 'tea',
    image: '/products/tea/green-tea-110g.jpg',
    description: 'Refreshing green tea leaves in a 110g pack.',
    weight: '110g',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'green-tea-250g',
    title: 'Green Tea (250g)',
    slug: 'green-tea-250g',
    category: 'tea',
    image: '/products/tea/green-tea-250g.jpg',
    description: 'Refreshing green tea leaves in a value 250g pack.',
    weight: '250g',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'lemongrass-tea',
    title: 'Lemon Grass Tea',
    slug: 'lemongrass-tea',
    category: 'tea',
    image: '/products/tea/lemongrass-tea.jpg',
    description: 'Aromatic lemon grass herbal tea, naturally caffeine-free.',
    weight: '100g',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'pink-tea',
    title: 'Pink Tea (Kashmiri Chai)',
    slug: 'pink-tea',
    category: 'tea',
    image: '/products/tea/pink-tea.jpg',
    description: 'Traditional Kashmiri pink tea blend for a rich, creamy cup.',
    weight: '190g',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'honey-500g',
    title: 'Natural Honey (500g)',
    slug: 'honey-500g',
    category: 'honey',
    image: '/products/honey/honey-500g.png',
    description: 'Pure natural honey packed for retail and export.',
    weight: '500g',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'honey-1kg',
    title: 'Natural Honey (1kg)',
    slug: 'honey-1kg',
    category: 'honey',
    image: '/products/honey/honey-1kg.png',
    description: 'Pure natural honey in a family-size 1kg jar.',
    weight: '1kg',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'rose-arq',
    title: 'Rose Arq',
    slug: 'rose-arq',
    category: 'arqiyaat',
    image: null,
    description: 'Traditional rose arq with clean aroma and taste.',
    weight: '800ml',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'food-essentials',
    title: 'Food Essentials',
    slug: 'food-essentials',
    category: 'miscellanous',
    image: null,
    description: 'Selected grocery essentials for varied buyer needs.',
    weight: 'Assorted',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'saag-halwa-pack',
    title: 'Saag/Halwa Pack',
    slug: 'saag-halwa-pack',
    category: 'exclusive-products-saag-halwa',
    image: null,
    description: 'Exclusive traditional food range for seasonal demand.',
    weight: '1kg',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'kitchenware-set',
    title: 'Kitchenware Set',
    slug: 'kitchenware-set',
    category: 'utensils-kitchenware',
    image: null,
    description: 'Useful kitchenware items for daily household needs.',
    weight: 'Assorted',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'mango-pickle',
    title: 'Mango Pickle (Achar)',
    slug: 'mango-pickle',
    category: 'pickle-achar',
    image: '/products/pickle-achar/mango-pickle.png',
    description: 'Traditional spicy mango pickle prepared the authentic way.',
    weight: '1kg',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'soy-sauce',
    title: 'Soy Sauce',
    slug: 'soy-sauce',
    category: 'sauces',
    image: '/products/sauces/soy-sauce.png',
    description: 'Rich soy sauce for cooking, marinades and food service use.',
    weight: '280ml / 9.47oz',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'synthetic-vinegar',
    title: 'Synthetic Vinegar',
    slug: 'synthetic-vinegar',
    category: 'sauces',
    image: '/products/sauces/synthetic-vinegar.png',
    description: 'Clear synthetic vinegar for pickling, cooking and cleaning.',
    weight: '285ml / 10oz',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'fried-onion',
    title: 'Fried Onion',
    slug: 'fried-onion',
    category: 'fried-onion',
    image: '/products/fried-onion/fried-onion.jpg',
    description: 'Crispy golden fried onion flakes for biryani, salads and garnishing.',
    weight: '400gm',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'pink-salt',
    title: 'Himalayan Pink Salt',
    slug: 'pink-salt',
    category: 'himalayan-pink-salt',
    image: '/products/himalayan-pink-salt/pink-salt.jpg',
    description: 'Pure Himalayan pink salt, rich in natural minerals.',
    weight: 'Retail Pack',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'pink-salt-rock-jar',
    title: 'Himalayan Pink Salt Rock (Jar)',
    slug: 'pink-salt-rock-jar',
    category: 'himalayan-pink-salt',
    image: '/products/himalayan-pink-salt/pink-salt-rock-jar.jpg',
    description: 'Coarse Himalayan pink salt rock crystals in a resealable jar.',
    weight: 'Jar',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'far-far-circle',
    title: 'Far Far Circle Fryum',
    slug: 'far-far-circle',
    category: 'snacks',
    image: '/products/snacks/far-far-circle.jpg',
    description: 'Colourful circle fryum snack pellets, ready to fry and serve.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'far-far-star',
    title: 'Far Far Star Fryum',
    slug: 'far-far-star',
    category: 'snacks',
    image: '/products/snacks/far-far-star.jpg',
    description: 'Star-shaped fryum snack pellets, a fun crispy treat.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'far-far-okra',
    title: 'Far Far Okra Fryum',
    slug: 'far-far-okra',
    category: 'snacks',
    image: '/products/snacks/far-far-okra.jpg',
    description: 'Okra-style fryum snack pellets, crisp and light when fried.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'far-far-pipe-colour',
    title: 'Far Far Pipe Fryum (Colour)',
    slug: 'far-far-pipe-colour',
    category: 'snacks',
    image: '/products/snacks/far-far-pipe-colour.jpg',
    description: 'Colourful pipe-shaped fryum snack pellets.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'far-far-pipe-yellow',
    title: 'Far Far Pipe Fryum (Yellow)',
    slug: 'far-far-pipe-yellow',
    category: 'snacks',
    image: '/products/snacks/far-far-pipe-yellow.jpg',
    description: 'Yellow pipe-shaped fryum snack pellets.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'lahori-nimko-mix-jar',
    title: 'Lahori Nimko Mix (Jar)',
    slug: 'lahori-nimko-mix-jar',
    category: 'snacks',
    image: '/products/snacks/lahori-nimko-mix-jar.jpg',
    description: 'Classic Lahori nimko mix in a convenient resealable jar.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: true,
  },
  {
    id: 'bhujia-seve',
    title: 'Bhujia Seve Namkeen',
    slug: 'bhujia-seve',
    category: 'snacks',
    image: '/products/snacks/bhujia-seve.jpg',
    description: 'Fine crunchy bhujia seve namkeen for tea-time snacking.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'hot-mix',
    title: 'Hot Mix Namkeen',
    slug: 'hot-mix',
    category: 'snacks',
    image: '/products/snacks/hot-mix.jpg',
    description: 'Spicy hot mix namkeen with a bold flavour.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'lahori-nimko',
    title: 'Lahori Nimko Namkeen',
    slug: 'lahori-nimko',
    category: 'snacks',
    image: '/products/snacks/lahori-nimko.jpg',
    description: 'Traditional Lahori nimko namkeen blend.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'moong-daal',
    title: 'Moong Daal Namkeen',
    slug: 'moong-daal',
    category: 'snacks',
    image: '/products/snacks/moong-daal.jpg',
    description: 'Crispy fried moong daal, lightly salted.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'roasted-gram-jar',
    title: 'Roasted Gram (Jar)',
    slug: 'roasted-gram-jar',
    category: 'snacks',
    image: '/products/snacks/roasted-gram-jar.jpg',
    description: 'Wholesome roasted gram (chana) in a resealable jar.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'roasted-gram-without-skin',
    title: 'Roasted Gram Without Skin (Jar)',
    slug: 'roasted-gram-without-skin',
    category: 'snacks',
    image: '/products/snacks/roasted-gram-without-skin.jpg',
    description: 'Skinless roasted gram, smooth and easy to snack on.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'roasted-salted-corn',
    title: 'Roasted Salted Corn (Jar)',
    slug: 'roasted-salted-corn',
    category: 'snacks',
    image: '/products/snacks/roasted-salted-corn.jpg',
    description: 'Crunchy roasted salted corn kernels.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: false,
  },
  {
    id: 'roasted-sweet-corn',
    title: 'Roasted Sweet Corn (Jar)',
    slug: 'roasted-sweet-corn',
    category: 'snacks',
    image: '/products/snacks/roasted-sweet-corn.jpg',
    description: 'Crunchy roasted sweet corn kernels with a hint of sweetness.',
    weight: '14oz / 400gm',
    origin: 'Pakistan',
    featured: false,
  },
]

export function getCategory(slug) {
  return categories.find(c => c.slug === slug) || null
}

export function getProductsByCategory(slug) {
  const category = getCategory(slug)
  return products.filter(p => p.category === slug || p.category === category?.id)
}

export function getProduct(slug) {
  return products.find(p => p.slug === slug) || null
}
